# Generated by Django 3.2.5 on 2021-09-10 07:23

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cats', multiselectfield.db.fields.MultiSelectField(choices=[('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Security', 'Security'), ('Data Science/Analytics', 'Data Science/Analytics'), ('Software Development', 'Software Development'), ('Computer Networking', 'Computer Networking'), ('Frontend Development', 'Frontend Development'), ('Backend development', 'Backend development'), ('Mobile Development', 'Mobile Development'), ('Desktop Development', 'Desktop Development'), ('DevOps Development', 'DevOps Development'), ('Game Development', 'Game Development'), ('Web Development', 'Web Development'), ('Cryptography Development', 'Cryptography Development'), ('CryptoCurrnecy Development', 'CryptoCurrnecy Development'), ('BlockChain Development', 'BlockChain Development'), ('Database Development', 'Database Development')], max_length=345)),
            ],
        ),
        migrations.CreateModel(
            name='LangTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langtags', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Php', 'Php'), ('Wordpress', 'Wordpress'), ('BootStrap', 'BootStrap'), ('Html & Css', 'Html & Css'), ('SQLite', 'SQLite'), ('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('C#', 'C#'), ('Git', 'Git'), ('Docker', 'Docker'), ('Sass', 'Sass'), ('Scss', 'Scss'), ('R', 'R'), ('Kotlin', 'Kotlin'), ('Go', 'Go'), ('C++', 'C++'), ('C', 'C'), ('JSON(API)', 'JSON(API)'), ('Ajax', 'Ajax'), ('AngularJS', 'AngularJS'), ('React', 'React'), ('JQuery', 'JQuery'), ('Vue', 'Vue'), ('Node.js', 'Node.js'), ('Raspberrypi', 'Raspberrypi'), ('ASP', 'ASP'), ('Django', 'Django'), ('Express.js', 'Express.js'), ('Flask', 'Flask'), ('CherryPy', 'CherryPy'), ('GraphQL', 'GraphQL'), ('TensorFlow', 'TensorFlow'), ('Pandas', 'Pandas'), ('Numpy', 'Numpy'), ('PyTorch', 'PyTorch'), ('Keras', 'Keras'), ('Theano', 'Theano'), ('MatPlotLib', 'MatPlotLib'), ('SciPy', 'SciPy'), ('PyGame', 'PyGame'), ('BS4', 'BS4'), ('Pillow', 'Pillow'), ('Meteor', 'Meteor'), ('Next.js', 'Next.js'), ('Ionic', 'Ionic'), ('Winjs', 'Winjs'), ('Selenium', 'Selenium'), ('OpenCV', 'OpenCV'), ('Dojo', 'Dojo'), ('Velocity.js', 'Velocity.js')], max_length=370)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت')),
                ('status', models.CharField(choices=[('draft', 'در حال انتظار'), ('published', 'منتشر شده')], default='draft', max_length=60, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('url', models.URLField(max_length=100)),
                ('stars', models.IntegerField(default=0)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('summary', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('video', models.URLField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category')),
                ('langtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.langtag')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Insertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_link', models.URLField(verbose_name='لینک پروژه شما')),
                ('your_email', models.EmailField(max_length=254, verbose_name='ایمیل شما :)')),
                ('cats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertions', to='blog.category')),
                ('langtags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertions', to='blog.langtag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
