# Generated by Django 3.2.5 on 2021-09-10 07:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='langtag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Php', 'Php'), ('Wordpress', 'Wordpress'), ('BootStrap', 'BootStrap'), ('Html & Css', 'Html & Css'), ('SQLite', 'SQLite'), ('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('C#', 'C#'), ('Git', 'Git'), ('Docker', 'Docker'), ('Sass', 'Sass'), ('Scss', 'Scss'), ('R', 'R'), ('Kotlin', 'Kotlin'), ('Go', 'Go'), ('C++', 'C++'), ('C', 'C'), ('JSON(API)', 'JSON(API)'), ('Ajax', 'Ajax'), ('AngularJS', 'AngularJS'), ('React', 'React'), ('JQuery', 'JQuery'), ('Vue', 'Vue'), ('Node.js', 'Node.js'), ('Raspberrypi', 'Raspberrypi'), ('ASP', 'ASP'), ('Django', 'Django'), ('Express.js', 'Express.js'), ('Flask', 'Flask'), ('CherryPy', 'CherryPy'), ('GraphQL', 'GraphQL'), ('TensorFlow', 'TensorFlow'), ('Pandas', 'Pandas'), ('Numpy', 'Numpy'), ('PyTorch', 'PyTorch'), ('Keras', 'Keras'), ('Theano', 'Theano'), ('MatPlotLib', 'MatPlotLib'), ('SciPy', 'SciPy'), ('PyGame', 'PyGame'), ('BS4', 'BS4'), ('Pillow', 'Pillow'), ('Meteor', 'Meteor'), ('Next.js', 'Next.js'), ('Ionic', 'Ionic'), ('Winjs', 'Winjs'), ('Selenium', 'Selenium'), ('OpenCV', 'OpenCV'), ('Dojo', 'Dojo'), ('Velocity.js', 'Velocity.js')], max_length=370),
        ),
    ]
