# Generated by Django 3.2.5 on 2021-09-10 07:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_langtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Security', 'Security'), ('Data Science/Analytics', 'Data Science/Analytics'), ('Software Development', 'Software Development'), ('Computer Networking', 'Computer Networking'), ('Frontend Development', 'Frontend Development'), ('Backend development', 'Backend development'), ('Mobile Development', 'Mobile Development'), ('Desktop Development', 'Desktop Development'), ('DevOps Development', 'DevOps Development'), ('Game Development', 'Game Development'), ('Web Development', 'Web Development'), ('Cryptography Development', 'Cryptography Development'), ('CryptoCurrnecy Development', 'CryptoCurrnecy Development'), ('BlockChain Development', 'BlockChain Development'), ('Database Development', 'Database Development')], max_length=345),
        ),
    ]
