# Generated by Django 3.2.5 on 2021-09-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_link', models.URLField(verbose_name='لینک پروژه شما')),
                ('your_email', models.EmailField(max_length=254, verbose_name='ایمیل شما :)')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertions', to='blog.category')),
                ('langtags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertions', to='blog.langtag')),
            ],
        ),
    ]
